# fly.toml app configuration file generated for locust-worker on 2024-03-17T19:20:20-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'locust-worker'
primary_region = 'bos'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
